### ISSUE TITLE
Multiple Entries with Same Key

### ISSUE THREAD

**Issue by Ryahn** [decebaldecebal/GeoActivity#2]
`java.lang.IllegalArgumentException: Multiple entries with same key: geoactivity=FMLMod:geoactivity{2.2.2} and geoactivity=FMLMod:geoactivity{2.1.1}`

We are building our 1.8.9 pack for Resonant Rise. We are running into this issue on our server when it tries to load up. 
https://pastebin.com/0kjuH8rj

I have also tried to downgrade the version to 2.2.1 but get this crash instead
https://pastebin.com/VH6a60MG

Not sure what is going on with it. I know there is only 1 geoactivity installed

EDIT:
It is doing it on the client as well
http://a.pomf.cat/wdcsbv.txt

**Comment by raress96** [comment]
Hm...It seems to be a very strange issue with ForgeGradle.I changed the package names and for some reason Gradle still compiled the old version also.Should be fixed now:
http://minecraft.curseforge.com/projects/geoactivity/files/2283131

I haven't had time to properly test it on the server, but it should work.Please update this issue if it doesn't.

**Comment by Ryahn** [comment]
Ok, so good news is that it loads now. But it crashes clients for Ticking Entity.
http://a.pomf.cat/olitrq.txt

Other than this error, the mod is working great and will most likely keep it in the pack once this is fixed.

**Comment by raress96** [comment]
I have narrowed it down and it seems to be a problem with the recently added JEI handler.I ran the game without JEI and it worked fine...
I will have to look into this and find out what is wrong.Will take some time since it works perfectly in the Dev environment...

**Comment by raress96** [comment]
New file is now up:
http://minecraft.curseforge.com/projects/geoactivity/files/2283172

I tested it in single player and it now works.I only tested the server in the dev environment though so please tell me if everything works as intended.

**Comment by Ryahn** [comment]
Works like a charm. Will report back if anything else comes up.
