### ISSUE TITLE
Blocks are invisible

### ISSUE THREAD

**Issue by Ryahn** [decebaldecebal/GeoActivity#3]
With the current setup we have in private testing. GeoActivity shows up in JEI and everything but when you place the blocks, they are invisible. The only way you know the block is there, is the grass block turns to dirt.

Here is the client side log that shows when placing the blocks down.
http://paste.resonant-rise.com:7777/afaworacul.avrasm

I can offer to have you test on our server if you want.

**Comment by raress96** [comment]
Do you have Optifine installed?
The blocks appear for me in my test client where I have only Jei and Geoactivity installed so maybe another mod causes this issue...

**Comment by Ryahn** [comment]
It looks like it was a mix of Optifine, betterfps and some other mod. We removed these and everything is working fine now.
